---
title: "MM_comparison_Chen2021"
output: html_notebook
---



```{r}
.libPaths("/exports/humgen/cnovellarausell/Rlibrary")
setwd("/exports/humgen/cnovellarausell/KidneyAtlas/bulkRNAseq/")
```







```{r}
library(tidyverse)
library(magrittr)
library(RColorBrewer)
library(pheatmap)
library(ggrepel)
library(viridis)
library(ComplexHeatmap)
```

```{r}
degs_atlas <- read_csv("/exports/humgen/cnovellarausell/KidneyAtlas/degs/degs_atlas_wilcox_SCVI.csv", col_types = cols(X1 = col_skip()))
```

```{r}
degs_atlas_mm <- read_csv("/exports/humgen/cnovellarausell/KidneyAtlas/metamarkers/pareto_markers_SCVI.csv", col_types = cols(X1 = col_skip()))
```


```{r}
tpm <- read.delim("/exports/humgen/cnovellarausell/KidneyAtlas/bulkRNAseq/GSE150338_Mouse_TPM_Replicates.txt", header=TRUE)
metadata <- tpm[,c("Gene_symbol")]
drops <- c("gene_id","Annotation", "Gene_symbol")
tpm <- tpm[ , !(names(tpm) %in% drops)]
tpm <- tpm[,1:64]
```






```{r}
col<-colnames(tpm)
col<-str_split(col, "_", simplify=TRUE)[,2]
annotation <- data.frame(Microdissected_CellType = col)
row.names(annotation) <- colnames(colnames(tpm))
colnames(tpm) <- col
```

```{r}
annotation$Microdissected_CellType = factor(annotation$Microdissected_CellType, levels = c("PTS1","PTS2","PTS3", "CTAL", "MTAL", "DTL1", "DTL2", "DTL3", "ATL", "CNT", "DCT"))
annotation <- annotation[order(annotation$Microdissected_CellType), ]
annotation.df <- data.frame(Microdissected_CellType = annotation)
```

```{r}
genes_mm <- degs_atlas_mm %>% 
group_by(cell_type) %>% slice(c(1:3)) %>% select(., c(gene, fold_change))
genes_mm <- genes_mm[genes_mm$cell_type %in% c("PTS1","PTS2","PTS3","DTL", "ATL", "MTAL", "CTAL","DCT", "CNT"),]
```



```{r}
write.csv(x=genes_mm, file="top3_genes_mm_heatmap.csv")
```


```{r}
genes_mm <- read.csv(file = "top3_genes_mm_heatmap.csv", colClasses=c("NULL", NA, NA))
```

```{r}
genes_mm <- genes_mm[!duplicated(genes_mm$gene),]
```


```{r}

library_order <- c("PTS1","PTS2","PTS3", "CTAL", "MTAL", "DTL", "ATL", "CNT", "DCT")
genes_mm <- genes_mm[order(match(genes_mm$cell_type, library_order)),]

```

```{r}
genes_mm<-genes_mm[,order(ncol(genes_mm):1)]
rownames(genes_mm) <- NULL
genes_mm <- subset(genes_mm, select=-c(1))
colnames(genes_mm) <- c("Genes", "Atlas_CellTypes")
```


```{r}
tpm <- as.matrix(sapply(tpm, as.numeric))
rownames(tpm) <- metadata
tpm <- log2(tpm+1)
tpm_mm <- tpm[unlist(genes_mm$Genes, use.names = F),]
tpm <- tpm[unlist(genes$Genes, use.names = F),]
```

```{r}
#Create a custom color scale
myColors <- brewer.pal(9,"Pastel1")
names(myColors) <- unique(genes_mm$Atlas_CellTypes)

my_colour = list(
    Atlas_CellTypes = myColors,
    Microdissected_CellType = c(myColors, DTL1 = "#DECBE4", DTL2 = "#DECBE4", DTL3 = "#DECBE4"))

pdf("bulk_rnaseq_heatmap_SCVI_mm.pdf")
pheatmap(tpm_mm, scale="row", annotation_col = annotation, cluster_rows = F, cluster_cols=F,
         angle_col = "45", annotation_colors = my_colour, color=viridis(5), annotation_names_row=F, annotation_names_col=F)
dev.off()
```